# Generated by Django 5.2 on 2025-04-10 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(max_length=100)),
                ('quote_text', models.TextField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='insights.assessment')),
            ],
        ),
    ]

# touched on 2025-05-27T15:29:02.327358Z
# touched on 2025-05-27T15:29:07.768872Z
# touched on 2025-05-27T15:29:10.581028Z
# touched on 2025-07-09T21:53:54.145290Z
# touched on 2025-07-09T21:53:57.725952Z
# touched on 2025-07-09T21:54:02.329294Z
# touched on 2025-07-09T21:54:14.005088Z
# touched on 2025-07-09T21:54:23.046279Z
# touched on 2025-07-09T21:54:35.087626Z
# touched on 2025-07-09T21:54:40.534126Z
# touched on 2025-07-09T21:54:53.929733Z
# touched on 2025-07-09T21:55:06.485971Z
# touched on 2025-07-09T21:55:08.648140Z
# touched on 2025-07-09T21:55:24.275147Z
# touched on 2025-07-09T21:55:27.417549Z
# touched on 2025-07-09T21:55:50.488592Z
# touched on 2025-07-09T21:55:57.336813Z
# touched on 2025-07-09T21:56:00.205430Z
# touched on 2025-07-09T21:56:12.465332Z
# touched on 2025-07-09T21:56:26.176343Z
# touched on 2025-07-09T21:56:40.072308Z
# touched on 2025-07-09T21:56:54.148292Z
# touched on 2025-07-09T21:56:59.320354Z
# touched on 2025-07-09T21:57:08.212665Z
# touched on 2025-07-09T21:57:14.841757Z
# touched on 2025-07-09T21:57:49.278767Z