# Generated by Django 5.2 on 2025-04-10 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_scores', to='insights.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(max_length=100)),
                ('matched_phrase', models.CharField(max_length=255)),
                ('input_phrase', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='insights.assessment')),
            ],
        ),
    ]

# touched on 2025-05-27T15:29:05.130444Z
# touched on 2025-07-09T21:53:57.725708Z
# touched on 2025-07-09T21:54:16.342672Z
# touched on 2025-07-09T21:54:27.831301Z
# touched on 2025-07-09T21:54:30.475045Z
# touched on 2025-07-09T21:54:44.928306Z
# touched on 2025-07-09T21:55:04.333029Z
# touched on 2025-07-09T21:55:27.417990Z
# touched on 2025-07-09T21:55:44.117402Z
# touched on 2025-07-09T21:55:48.179932Z
# touched on 2025-07-09T21:55:50.488076Z
# touched on 2025-07-09T21:56:02.775208Z